services:
  - type: web
    name: taskpro-manager
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_SECRET
        sync: false
      - key: PORT
        value: 10000
